import { createHash } from "node:crypto";
import type { DbPool } from "../db/pool.js";

/**
 * Selects all enabled pipelines whose `selector` is a subset of the given
 * collector attributes (jsonb containment: collector_attrs @> pipeline.selector),
 * orders them deterministically by name, and concatenates their current
 * content into the single Alloy config that gets returned by GetConfig.
 *
 * Ordering matters because components that declare `prometheus.scrape` etc.
 * are order-sensitive only in how they reference each other — but the hash we
 * return to the collector MUST be stable, so we sort by name.
 *
 * The concatenation strategy is "comment banner + raw content" (not wrapped
 * in `declare` blocks). Grafana Cloud Fleet Management wraps pipelines in
 * `declare` blocks for namespace isolation, but that requires the operator to
 * author pipelines as reusable components. For MVP we keep it literal: the
 * pipeline content is spliced verbatim into the final config. If you want
 * namespacing, include the `declare "foo" { ... } foo "default" {}` yourself.
 */
export interface AssembledConfig {
  content: string;
  hash: string;
  pipeline_names: string[];
}

export async function assembleConfigFor(
  db: DbPool,
  localAttributes: Record<string, string>,
): Promise<AssembledConfig> {
  const r = await db.query<{
    name: string;
    current_content: string;
    current_version: number;
    current_hash: string;
  }>(
    `
    SELECT name, current_content, current_version, current_hash
    FROM pipelines
    WHERE enabled = true AND $1::jsonb @> selector
    ORDER BY name
    `,
    [JSON.stringify(localAttributes)],
  );

  if (r.rows.length === 0) {
    return {
      content: "// No matching pipelines for this collector.\n",
      hash: sha256("// No matching pipelines for this collector.\n"),
      pipeline_names: [],
    };
  }

  const parts: string[] = [
    "// Generated by Alloy Fleet Manager. Do not edit by hand.",
    `// Pipelines matched: ${r.rows.map((p) => `${p.name}@${p.current_version}`).join(", ")}`,
    "",
  ];
  for (const p of r.rows) {
    parts.push(`// --- pipeline: ${p.name} (version ${p.current_version}) ---`);
    parts.push(p.current_content.trimEnd());
    parts.push("");
  }
  const content = parts.join("\n");

  // Hash includes all per-pipeline hashes + order, so any change to a matched
  // pipeline OR a change to which pipelines match flips the hash.
  const hasher = createHash("sha256");
  for (const p of r.rows) {
    hasher.update(p.name);
    hasher.update("\0");
    hasher.update(p.current_hash);
    hasher.update("\0");
  }
  return { content, hash: hasher.digest("hex"), pipeline_names: r.rows.map((p) => p.name) };
}

export function sha256(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}
